[home]
titulo = "Painel de preços de combustíveis"
subtitulo = "Introdução ao dataset"
introducao_painel = "O dataset de combustíveis é composto por dados que vão de julho de 2001 até janeiro de 2023. Estes dados incluem preços mínimos, máximos e médios, registrados mensalmente por estado da federação. Os tipos de combustíveis contemplados são: gasolina comum e aditivada, etanol, diesel, diesel S10 (ou DS10), gás de cozinha e gás natural."

introducao_dataset = "Trazemos aqui neste dashboard uma análise exploratória dos dados de preços de combustíveis. Através de visualizações interativas, é possível explorar os preços médios dos combustíveis por estado, por mês e ao longo do tempo. Além disso, é possível comparar os preços médios dos combustíveis entre os estados e visualizar a evolução dos preços ao longo dos anos."


[por_mes]
titulo = "Visualização por mês"
lbl_select_mes = "Selecione o ano mês de referência"
lbl_select_estado = "Selecione o estado"
lbl_preco_medio = "Preços médios do estado [#]"
lbl_gasolina_comum = "Gasolina comum"
lbl_gasolina_aditivada = "Gasolina aditivada"
lbl_etanol = "Etanol"
lbl_diesel = "Diesel"
lbl_diesel_s10 = "Diesel S10"
subtitulo_top5 = "Comparação dos TOP 5 meses com maiores médias de preços"


[por_timeseries]
titulo = "Visualização da série temporal"
